### PR TITLE
Newfeature

### PR DESCRIPTION
**Pull request by cimplesid**

### CODE REVIEW

**Comment by cimplesid** [comment]
why was this closed

**Comment by lohanidamodar** [comment]
Already merged, you opened new one after fixing bug, previous would work just fine

**Comment by cimplesid** [comment]
> Already merged, you opened new one after fixing bug, previous would work just fine

i have had added the gif in next commit and it is missing from main readme.md of the repo

**Comment by lohanidamodar** [comment]
It's already there in the develop branch! Not yet merged to the master branch!

**Pull request closed without merging**
